export const REQUEST_IP = 'REQUEST_CONVERSATIONS';
export const REQUEST_IP_ERROR = 'REQUEST_CONVERSATIONS_ERROR';
export const REQUEST_GEOLOCATION = 'REQUEST_GEOLOCATION';
export const REQUEST_GEOLOCATION_SUCCESS = 'REQUEST_GEOLOCATION_SUCCESS';
export const REQUEST_GEOLOCATION_ERROR = 'REQUEST_GEOLOCATION_ERROR';

